# 自動生成: tools/make-items.py(元は tools/item-catalog.py)。手で直さない。
class_name ForageData
extends RefCounted

## 自生物、魔物の素材、遺品の定義。ItemDB.ITEMS に併せて使う。税がかからないもの(燐晶ではない)。

const ITEMS := {
	"kuro_take": {"name": "黒茸", "kind": "consumable", "price": 10, "free": true, "use": "heal_pct", "v": 0.15, "min": 6.0, "desc": "灰を吸って黒くなった茸。壁下区の人々の主食。HPを15%回復する。"},
	"no_hai_imo": {"name": "野灰芋", "kind": "consumable", "price": 14, "free": true, "use": "heal_pct", "v": 0.25, "min": 8.0, "desc": "灰芋の野生種。固いが、煮れば甘い。HPを25%回復する。"},
	"yakusou": {"name": "洞窟薬草", "kind": "consumable", "price": 20, "free": true, "use": "heal_pct", "v": 0.30, "min": 10.0, "desc": "どの層にも生える苦い草。噛んで傷に当てる。HPを30%回復する。"},
	"koke_mitsu": {"name": "苔蜜", "kind": "consumable", "price": 36, "free": true, "use": "heal_pct", "v": 0.40, "min": 14.0, "desc": "苔の根もとに溜まる甘い蜜。腐らない。HPを40%回復する。"},
	"mekura_uo": {"name": "目なし魚", "kind": "consumable", "price": 24, "free": true, "use": "heal_pct", "v": 0.40, "min": 14.0, "desc": "水底に棲む、目のない白い魚。HPを40%回復する。"},
	"kotsufun_take": {"name": "骨粉茸", "kind": "consumable", "price": 34, "free": true, "use": "heal_pct", "v": 0.30, "min": 14.0, "desc": "骨の粉を吸って育つ白い茸。HPを30%回復する。"},
	"reimu_no_hana": {"name": "冷霧の花", "kind": "consumable", "price": 50, "free": true, "use": "heal_pct", "v": 0.50, "min": 20.0, "desc": "冷たい霧の中で咲く青い花。HPを50%回復する。"},
	"zui_mitsu": {"name": "髄蜜", "kind": "consumable", "price": 130, "free": true, "use": "heal_pct", "v": 1.00, "min": 30.0, "desc": "骨の髄に溜まる透き通った蜜。HPを全快させる。ごく稀。"},
	"nanashi_no_mi": {"name": "名なしの実", "kind": "consumable", "price": 150, "free": true, "use": "heal_pct", "v": 1.00, "min": 40.0, "desc": "食べても、何の味か言えない。HPを全快させる。"},
	"kemono_niku": {"name": "獣肉", "kind": "consumable", "price": 8, "free": true, "use": "heal_pct", "v": 0.20, "min": 8.0, "desc": "倒した獣の肉。胃袋スープの具。HPを20%回復する。"},
	"hikari_goke": {"name": "光苔", "kind": "consumable", "price": 14, "free": true, "use": "mp_pct", "v": 0.20, "desc": "壁一面を青白く光らせる苔。口に含むと、頭が冴える。MPを20%回復する。"},
	"shizuku_goke": {"name": "雫苔", "kind": "consumable", "price": 24, "free": true, "use": "mp_pct", "v": 0.30, "desc": "水を含んだ苔。絞ると、魔力を帯びた水が出る。MPを30%回復する。"},
	"sabi_mizu": {"name": "鉱水", "kind": "consumable", "price": 26, "free": true, "use": "mp_pct", "v": 0.35, "desc": "坑道の壁から滴る、金気のある水。MPを35%回復する。"},
	"mizukagami_so": {"name": "水鏡草", "kind": "consumable", "price": 40, "free": true, "use": "mp_pct", "v": 0.45, "desc": "水面に浮かぶ、鏡のような葉。MPを45%回復する。"},
	"tomoshi_take": {"name": "灯り茸", "kind": "consumable", "price": 16, "free": true, "use": "light", "v": 0.00, "t": 120.0, "desc": "かさが青白く光る茸。握っていると、120秒間、灯りの届く半径が2マス広がる。"},
	"yawaraka_hikari": {"name": "軟光", "kind": "consumable", "price": 80, "free": true, "use": "light", "v": 0.00, "t": 300.0, "desc": "壁に張りつく、柔らかい光の塊。300秒間、灯りの届く半径が2マス広がる。"},
	"kodo_nira": {"name": "坑道韮", "kind": "consumable", "price": 30, "free": true, "use": "buff", "buff": "power", "v": 1.20, "t": 60.0, "desc": "坑夫が力をつけるために噛む、辛い韮。60秒間、体当たりが2割強くなる。"},
	"tetsu_take": {"name": "鉄茸", "kind": "consumable", "price": 28, "free": true, "use": "buff", "buff": "guard", "v": 0.80, "t": 60.0, "desc": "鉄の味のする硬い茸。60秒間、受けるダメージが2割減る。"},
	"kagami_goke": {"name": "鏡苔", "kind": "consumable", "price": 32, "free": true, "use": "buff", "buff": "speed", "v": 1.20, "t": 45.0, "desc": "鏡の壁に生える、銀色の苔。45秒間、足が2割速くなる。"},
	"inori_goke": {"name": "祈りの苔", "kind": "consumable", "price": 55, "free": true, "use": "heal_pct", "v": 0.50, "min": 20.0, "desc": "骨の壁に生える白い苔。神殿が好んで買う。HPを50%回復する。"},
	"iki_take": {"name": "息茸", "kind": "consumable", "price": 90, "free": true, "use": "buff", "buff": "regen", "v": 0.50, "t": 30.0, "desc": "呼吸するように膨らんだり縮んだりする茸。30秒間で、最大HPの半分がじわじわ回復する。"},
	"nemuri_take": {"name": "眠り茸", "kind": "material", "price": 28, "free": true, "desc": "かさの胞子を吸うと眠くなる。眠り薬の原料。"},
	"sakebi_take": {"name": "叫び茸", "kind": "material", "price": 18, "free": true, "desc": "踏むと、甲高い音を立てる。魔物避けの鳴子の原料。"},
	"doku_take": {"name": "毒茸", "kind": "material", "price": 12, "free": true, "desc": "食べると死ぬ。毒消しと、毒矢の原料。"},
	"sabi_goke": {"name": "錆苔", "kind": "material", "price": 14, "free": true, "desc": "錆の上に生える橙色の苔。鍛冶組が、焼き入れに使う。"},
	"iwa_jio": {"name": "岩塩", "kind": "material", "price": 22, "free": true, "desc": "壁に白く吹き出す塩。荒野では、塩は高い。"},
	"komori_fun": {"name": "蝙蝠糞", "kind": "material", "price": 8, "free": true, "desc": "洞窟に積もる蝙蝠の糞。川沿いの畑の肥料になる。"},
	"mizu_hiru": {"name": "水蛭", "kind": "material", "price": 16, "free": true, "desc": "水ぎわの石に張りつく蛭。癒しの院が、血抜きに使う。"},
	"shinju_gai": {"name": "真珠貝", "kind": "material", "price": 55, "free": true, "desc": "水底の大きな貝。まれに、中に真珠がある。"},
	"shinju": {"name": "真珠", "kind": "material", "price": 300, "free": true, "desc": "真珠貝から出た珠。宝飾屋が高く買う。"},
	"sui_sho_mo": {"name": "水晶藻", "kind": "material", "price": 34, "free": true, "desc": "細かい結晶をまとった藻。ガラスの原料。"},
	"hone_no_hana": {"name": "骨の花", "kind": "material", "price": 70, "free": true, "desc": "骨の隙間に咲く、白い花。霊薬の素材として、西の森からも買いに来る。"},
	"furui_ko": {"name": "古い香", "kind": "material", "price": 45, "free": true, "desc": "骨の壁に染みた、古い樹脂の香。神殿が焚く。"},
	"byakuro": {"name": "白蝋", "kind": "material", "price": 30, "free": true, "desc": "骨から滲み出す白い蝋。灯具の芯に使う。"},
	"zugai_take": {"name": "頭蓋茸", "kind": "material", "price": 40, "free": true, "desc": "頭蓋の形をした茸。薬師組が、咳止めに使う。"},
	"kemono_kawa": {"name": "獣皮", "kind": "material", "price": 20, "free": true, "desc": "獣の毛皮。荒野では、革も布も、輸入に頼る。"},
	"kiba": {"name": "牙と爪", "kind": "material", "price": 14, "free": true, "desc": "獣の牙。細工物の素材。"},
	"nenneki": {"name": "粘液", "kind": "material", "price": 12, "free": true, "desc": "ウーズから採る粘液。接着剤と、磨き粉になる。"},
	"honekuzu": {"name": "骨片", "kind": "material", "price": 6, "free": true, "desc": "アンデッドの骨。骨粉にして、畑に撒く。"},
	"hakatsuchi": {"name": "墓土", "kind": "material", "price": 10, "free": true, "desc": "アンデッドに付いた土。神殿が清めて、買い取る。"},
	"tetsukuzu": {"name": "鉄屑", "kind": "material", "price": 12, "free": true, "desc": "壊れた魔導体の部品。鍛冶組が溶かす。"},
	"ma_ha": {"name": "魔草の葉", "kind": "material", "price": 14, "free": true, "desc": "動く草木から採れる葉。薬草より効く。"},
	"yakeishi": {"name": "焼け石", "kind": "material", "price": 20, "free": true, "desc": "精霊が崩れた跡に残る、熱い石。燃料になる。"},
	"uroko": {"name": "魔物の鱗", "kind": "material", "price": 40, "free": true, "desc": "硬い鱗。鎧の継ぎ目に使う。"},
	"doku_sen": {"name": "毒腺", "kind": "material", "price": 32, "free": true, "desc": "蜘蛛や蛇の毒の袋。薬師組が、毒消しに加工する。"},
	"hane": {"name": "羽", "kind": "material", "price": 12, "free": true, "desc": "飛ぶ魔物の羽。矢羽や、飾りになる。"},
	"relic_gear": {"name": "遺品の装備", "kind": "material", "price": 90, "free": true, "desc": "先に来た者の装備一式。ギルドの遺品課に届けると、謝礼が出る。"},
	"relic_tools": {"name": "遺品の道具", "kind": "material", "price": 40, "free": true, "desc": "錆びていない道具一揃い。"},
	"relic_tag": {"name": "認識票", "kind": "material", "price": 50, "free": true, "desc": "冒険者の首にかかっていた札。遺族に届けると、謝礼が出る。"},
	"relic_coins": {"name": "古い銀貨", "kind": "material", "price": 15, "free": true, "desc": "袋に残っていた、少しの銀貨。"},
}

## 舞台ごとの出現。[品物, 重み, 場所, 最も浅い層]
const SPOTS := {
	"fuyou": [
		["kuro_take", 3.00, "floor", 1],
		["no_hai_imo", 2.00, "floor", 1],
		["koke_mitsu", 1.00, "wall", 1],
		["hikari_goke", 3.00, "wall", 1],
		["shizuku_goke", 2.00, "wall", 1],
		["tomoshi_take", 3.00, "wall", 1],
		["nemuri_take", 1.50, "floor", 1],
		["sakebi_take", 1.50, "floor", 1],
		["doku_take", 2.00, "floor", 1],
		["komori_fun", 1.00, "floor", 1],
	],
	"sabi": [
		["kuro_take", 2.00, "floor", 1],
		["no_hai_imo", 3.00, "floor", 1],
		["sabi_mizu", 1.50, "wall", 3],
		["kodo_nira", 2.00, "floor", 3],
		["tetsu_take", 2.00, "floor", 3],
		["doku_take", 1.00, "floor", 3],
		["sabi_goke", 3.00, "wall", 3],
		["iwa_jio", 2.50, "wall", 3],
		["komori_fun", 2.00, "floor", 3],
	],
	"kagami": [
		["kuro_take", 1.00, "floor", 1],
		["mekura_uo", 3.00, "water", 3],
		["reimu_no_hana", 1.00, "floor", 3],
		["hikari_goke", 1.00, "wall", 3],
		["shizuku_goke", 2.00, "wall", 3],
		["mizukagami_so", 3.00, "water", 3],
		["kagami_goke", 2.00, "wall", 3],
		["iwa_jio", 0.50, "wall", 5],
		["mizu_hiru", 2.00, "water", 3],
		["shinju_gai", 2.00, "water", 3],
		["shinju", 0.12, "water", 5],
		["sui_sho_mo", 1.50, "water", 3],
	],
	"generic": [
		["kuro_take", 2.00, "floor", 1],
		["no_hai_imo", 1.00, "floor", 1],
	],
	"all": [
		["yakusou", 1.50, "floor", 1],
	],
	"hone": [
		["kotsufun_take", 3.00, "floor", 7],
		["zui_mitsu", 0.60, "wall", 7],
		["tomoshi_take", 1.00, "wall", 7],
		["inori_goke", 2.00, "wall", 7],
		["hone_no_hana", 1.50, "floor", 7],
		["furui_ko", 2.00, "wall", 7],
		["byakuro", 2.50, "floor", 7],
		["zugai_take", 1.00, "wall", 7],
	],
	"soko": [
		["nanashi_no_mi", 1.00, "floor", 10],
		["tomoshi_take", 1.00, "wall", 10],
		["yawaraka_hikari", 2.00, "wall", 10],
		["iki_take", 3.00, "floor", 10],
	],
}

## 魔物が落とすもの。[対象, 品物, 確率]。対象は type:○○ か idx:○○(index に含まれる語)
const DROPS := [
	["type:beast", "kemono_niku", 0.30],
	["type:beast", "kemono_kawa", 0.18],
	["type:beast", "kiba", 0.20],
	["type:ooze", "nenneki", 0.45],
	["type:undead", "honekuzu", 0.40],
	["type:undead", "hakatsuchi", 0.20],
	["type:construct", "tetsukuzu", 0.50],
	["type:plant", "ma_ha", 0.45],
	["type:fey", "ma_ha", 0.30],
	["type:elemental", "yakeishi", 0.45],
	["type:dragon", "uroko", 0.50],
	["type:monstrosity", "uroko", 0.15],
	["type:monstrosity", "kiba", 0.20],
	["type:fiend", "yakeishi", 0.25],
	["idx:spider", "doku_sen", 0.35],
	["idx:snake", "doku_sen", 0.30],
	["idx:bat", "hane", 0.25],
	["idx:eagle", "hane", 0.35],
	["idx:owl", "hane", 0.35],
	["idx:raven", "hane", 0.35],
	["idx:hawk", "hane", 0.35],
	["idx:harpy", "hane", 0.40],
]

## 燐晶の純度。[id, 名前, 銀貨/kg]
const PURITIES := [
	["low", "低", 30],
	["mid", "並", 50],
	["high", "高", 80],
	["pure", "極", 140],
	["unk", "不明", 200],
]
