"""アイテム(燐晶、迷宮に自生するもの、魔物の素材、遺品、既存の消耗品)の一覧。
make-items.py が、これを読んで、アイコンのシート、索引、GDScript のデータ(scripts/items_forage.gd)を作る。
値段は銀貨。売値は、値段の4割(ItemDB.SELL_RATE)。

自生物(FORAGE)と魔物の素材(DROPS)と遺品は、燐晶ではないので、税がかからない(燐晶税は、持ち帰った燐晶だけ)。
spots: (舞台, 重み, 場所, 最も浅い層)
  場所: floor=部屋の床 / wall=壁ぎわ / water=水ぎわ(水の舞台) / corr=通路
  舞台: fuyou sabi kagami hone soko generic、all は全舞台
"""

# ---- 燐晶の純度。値段は 1kg あたりの銀貨(docs/urbs-labyrinthi-spec.md §3.4) ----
PURITIES = [
    # id, 名前, 銀貨/kg
    ("low", "低", 30),
    ("mid", "並", 50),
    ("high", "高", 80),
    ("pure", "極", 140),
    ("unk", "不明", 200),
]
CRYSTAL_SIZES = ["s", "m", "l"]   # 欠片、かたまり、大きな塊

# ---- 既存の消耗品(絵だけ) ----
EXISTING = [
    ("potion", "bottle", dict(liquid="d84a5a")),
    ("hi_potion", "bottle", dict(liquid="ff7a9a", big=True, glow=True)),
    ("ether", "bottle", dict(liquid="4a8ae0")),
    ("revive_charm", "charm", dict(col="f0d878")),
    ("lamp_oil", "bottle", dict(liquid="f0e060", flask=True)),
    ("return_scroll", "scroll", dict(col="e8dcb0")),
]

# ---- 迷宮に自生するもの(税がかからない) ----
FORAGE = [
    # --- 食べ物・回復 ---
    dict(id="kuro_take", name="黒茸", price=10, use="heal_pct", v=0.15, min=6,
         desc="灰を吸って黒くなった茸。壁下区の人々の主食。HPを15%回復する。",
         spots=[("fuyou", 3, "floor", 1), ("sabi", 2, "floor", 1), ("kagami", 1, "floor", 1), ("generic", 2, "floor", 1)],
         icon=("mushroom", dict(cap="3a3a46", stem="8a8a96", dots="6a6a7a", n=2))),
    dict(id="no_hai_imo", name="野灰芋", price=14, use="heal_pct", v=0.25, min=8,
         desc="灰芋の野生種。固いが、煮れば甘い。HPを25%回復する。",
         spots=[("fuyou", 2, "floor", 1), ("sabi", 3, "floor", 1), ("generic", 1, "floor", 1)],
         icon=("tuber", dict(col="8a8a96", sprout="6aa050"))),
    dict(id="yakusou", name="洞窟薬草", price=20, use="heal_pct", v=0.30, min=10,
         desc="どの層にも生える苦い草。噛んで傷に当てる。HPを30%回復する。",
         spots=[("all", 1.5, "floor", 1)],
         icon=("herb", dict(col="5aa860", flower="e8e8a0"))),
    dict(id="koke_mitsu", name="苔蜜", price=36, use="heal_pct", v=0.40, min=14,
         desc="苔の根もとに溜まる甘い蜜。腐らない。HPを40%回復する。",
         spots=[("fuyou", 1, "wall", 1)],
         icon=("jar", dict(col="e8b838", lid="7a5a2a"))),
    dict(id="mekura_uo", name="目なし魚", price=24, use="heal_pct", v=0.40, min=14,
         desc="水底に棲む、目のない白い魚。HPを40%回復する。",
         spots=[("kagami", 3, "water", 3)],
         icon=("fish", dict(col="d8e0e8"))),
    dict(id="kotsufun_take", name="骨粉茸", price=34, use="heal_pct", v=0.30, min=14,
         desc="骨の粉を吸って育つ白い茸。HPを30%回復する。",
         spots=[("hone", 3, "floor", 7)],
         icon=("mushroom", dict(cap="e8e4d0", stem="c8c4b0", dots="b0ac98", n=1, tall=True))),
    dict(id="reimu_no_hana", name="冷霧の花", price=50, use="heal_pct", v=0.50, min=20,
         desc="冷たい霧の中で咲く青い花。HPを50%回復する。",
         spots=[("kagami", 1, "floor", 3)],
         icon=("flower", dict(petal="8ad8f0", center="f0f8ff"))),
    dict(id="zui_mitsu", name="髄蜜", price=130, use="heal_pct", v=1.0, min=30,
         desc="骨の髄に溜まる透き通った蜜。HPを全快させる。ごく稀。",
         spots=[("hone", 0.6, "wall", 7)],
         icon=("jar", dict(col="f0e0a0", lid="c8c4b0", glow=True))),
    dict(id="nanashi_no_mi", name="名なしの実", price=150, use="heal_pct", v=1.0, min=40,
         desc="食べても、何の味か言えない。HPを全快させる。",
         spots=[("soko", 1, "floor", 10)],
         icon=("fruit", dict(col="a890ff", leaf="504880"))),
    dict(id="kemono_niku", name="獣肉", price=8, use="heal_pct", v=0.20, min=8,
         desc="倒した獣の肉。胃袋スープの具。HPを20%回復する。",
         icon=("meat", dict(col="c04a4a"))),
    # --- 魔力・灯り ---
    dict(id="hikari_goke", name="光苔", price=14, use="mp_pct", v=0.20,
         desc="壁一面を青白く光らせる苔。口に含むと、頭が冴える。MPを20%回復する。",
         spots=[("fuyou", 3, "wall", 1), ("kagami", 1, "wall", 3)],
         icon=("moss", dict(col="4a9a8a", glow="a8f0d8"))),
    dict(id="shizuku_goke", name="雫苔", price=24, use="mp_pct", v=0.30,
         desc="水を含んだ苔。絞ると、魔力を帯びた水が出る。MPを30%回復する。",
         spots=[("fuyou", 2, "wall", 1), ("kagami", 2, "wall", 3)],
         icon=("moss", dict(col="3a7a9a", glow="a8e0ff", drops=True))),
    dict(id="sabi_mizu", name="鉱水", price=26, use="mp_pct", v=0.35,
         desc="坑道の壁から滴る、金気のある水。MPを35%回復する。",
         spots=[("sabi", 1.5, "wall", 3)],
         icon=("bottle", dict(liquid="a0a8c0", flask=True))),
    dict(id="mizukagami_so", name="水鏡草", price=40, use="mp_pct", v=0.45,
         desc="水面に浮かぶ、鏡のような葉。MPを45%回復する。",
         spots=[("kagami", 3, "water", 3)],
         icon=("herb", dict(col="8ad0e0", flower="f0f8ff", round=True))),
    dict(id="tomoshi_take", name="灯り茸", price=16, use="light", t=120,
         desc="かさが青白く光る茸。握っていると、120秒間、灯りの届く半径が2マス広がる。",
         spots=[("fuyou", 3, "wall", 1), ("hone", 1, "wall", 7), ("soko", 1, "wall", 10)],
         icon=("mushroom", dict(cap="8ad8f0", stem="d8f0f8", dots="f0ffff", glow="8ad8f0", n=2))),
    dict(id="yawaraka_hikari", name="軟光", price=80, use="light", t=300,
         desc="壁に張りつく、柔らかい光の塊。300秒間、灯りの届く半径が2マス広がる。",
         spots=[("soko", 2, "wall", 10)],
         icon=("slime", dict(col="c8c0ff", glow=True))),
    # --- 強化 ---
    dict(id="kodo_nira", name="坑道韮", price=30, use="buff", buff="power", v=1.2, t=60,
         desc="坑夫が力をつけるために噛む、辛い韮。60秒間、体当たりが2割強くなる。",
         spots=[("sabi", 2, "floor", 3)],
         icon=("herb", dict(col="7ab050", flower=None, blade=True))),
    dict(id="tetsu_take", name="鉄茸", price=28, use="buff", buff="guard", v=0.8, t=60,
         desc="鉄の味のする硬い茸。60秒間、受けるダメージが2割減る。",
         spots=[("sabi", 2, "floor", 3)],
         icon=("mushroom", dict(cap="8a6a58", stem="a09088", dots="c0a898", n=1))),
    dict(id="kagami_goke", name="鏡苔", price=32, use="buff", buff="speed", v=1.2, t=45,
         desc="鏡の壁に生える、銀色の苔。45秒間、足が2割速くなる。",
         spots=[("kagami", 2, "wall", 3)],
         icon=("moss", dict(col="a8b8c8", glow="e8f4ff"))),
    dict(id="inori_goke", name="祈りの苔", price=55, use="heal_pct", v=0.50, min=20,
         desc="骨の壁に生える白い苔。神殿が好んで買う。HPを50%回復する。",
         spots=[("hone", 2, "wall", 7)],
         icon=("moss", dict(col="d8d8c0", glow="fff8d0"))),
    dict(id="iki_take", name="息茸", price=90, use="buff", buff="regen", v=0.5, t=30,
         desc="呼吸するように膨らんだり縮んだりする茸。30秒間で、最大HPの半分がじわじわ回復する。",
         spots=[("soko", 3, "floor", 10)],
         icon=("mushroom", dict(cap="c898f0", stem="e8d8ff", dots="ffffff", glow="c898f0", n=1, tall=True))),
    # --- 素材(薬師組、鍛冶組、神殿などが買う) ---
    dict(id="nemuri_take", name="眠り茸", price=28, kind="material",
         desc="かさの胞子を吸うと眠くなる。眠り薬の原料。",
         spots=[("fuyou", 1.5, "floor", 1)],
         icon=("mushroom", dict(cap="9a78c8", stem="d8c8e8", dots="e8d8f8", n=2))),
    dict(id="sakebi_take", name="叫び茸", price=18, kind="material",
         desc="踏むと、甲高い音を立てる。魔物避けの鳴子の原料。",
         spots=[("fuyou", 1.5, "floor", 1)],
         icon=("mushroom", dict(cap="e0605a", stem="f0e0d0", dots="f8f0e0", n=1, tall=True))),
    dict(id="doku_take", name="毒茸", price=12, kind="material",
         desc="食べると死ぬ。毒消しと、毒矢の原料。",
         spots=[("fuyou", 2, "floor", 1), ("sabi", 1, "floor", 3)],
         icon=("mushroom", dict(cap="c83a8a", stem="e8d0d8", dots="f8e0f0", n=2))),
    dict(id="sabi_goke", name="錆苔", price=14, kind="material",
         desc="錆の上に生える橙色の苔。鍛冶組が、焼き入れに使う。",
         spots=[("sabi", 3, "wall", 3)],
         icon=("moss", dict(col="c07a3a", glow=None))),
    dict(id="iwa_jio", name="岩塩", price=22, kind="material",
         desc="壁に白く吹き出す塩。荒野では、塩は高い。",
         spots=[("sabi", 2.5, "wall", 3), ("kagami", 0.5, "wall", 5)],
         icon=("lump", dict(col="e8e8f0", kind="salt"))),
    dict(id="komori_fun", name="蝙蝠糞", price=8, kind="material",
         desc="洞窟に積もる蝙蝠の糞。川沿いの畑の肥料になる。",
         spots=[("sabi", 2, "floor", 3), ("fuyou", 1, "floor", 1)],
         icon=("lump", dict(col="5a4a3a", kind="dung"))),
    dict(id="mizu_hiru", name="水蛭", price=16, kind="material",
         desc="水ぎわの石に張りつく蛭。癒しの院が、血抜きに使う。",
         spots=[("kagami", 2, "water", 3)],
         icon=("slime", dict(col="6a4a58", leech=True))),
    dict(id="shinju_gai", name="真珠貝", price=55, kind="material",
         desc="水底の大きな貝。まれに、中に真珠がある。",
         spots=[("kagami", 2, "water", 3)],
         icon=("shell", dict(col="d8d0e8"))),
    dict(id="shinju", name="真珠", price=300, kind="material",
         desc="真珠貝から出た珠。宝飾屋が高く買う。",
         spots=[("kagami", 0.12, "water", 5)],
         icon=("pearl", dict())),
    dict(id="sui_sho_mo", name="水晶藻", price=34, kind="material",
         desc="細かい結晶をまとった藻。ガラスの原料。",
         spots=[("kagami", 1.5, "water", 3)],
         icon=("moss", dict(col="88c0d0", glow="e8ffff", crystal=True))),
    dict(id="hone_no_hana", name="骨の花", price=70, kind="material",
         desc="骨の隙間に咲く、白い花。霊薬の素材として、西の森からも買いに来る。",
         spots=[("hone", 1.5, "floor", 7)],
         icon=("flower", dict(petal="e8e4d0", center="a0988a", bone=True))),
    dict(id="furui_ko", name="古い香", price=45, kind="material",
         desc="骨の壁に染みた、古い樹脂の香。神殿が焚く。",
         spots=[("hone", 2, "wall", 7)],
         icon=("lump", dict(col="d89a3a", kind="resin"))),
    dict(id="byakuro", name="白蝋", price=30, kind="material",
         desc="骨から滲み出す白い蝋。灯具の芯に使う。",
         spots=[("hone", 2.5, "floor", 7)],
         icon=("lump", dict(col="f4f0e0", kind="wax"))),
    dict(id="zugai_take", name="頭蓋茸", price=40, kind="material",
         desc="頭蓋の形をした茸。薬師組が、咳止めに使う。",
         spots=[("hone", 1, "wall", 7)],
         icon=("mushroom", dict(cap="e0dcc8", stem="b0ac98", dots="3a3640", n=1, skull=True))),
    # --- 魔物の素材(倒すと落ちる) ---
    dict(id="kemono_kawa", name="獣皮", price=20, kind="material",
         desc="獣の毛皮。荒野では、革も布も、輸入に頼る。", icon=("pelt", dict(col="8a6a48"))),
    dict(id="kiba", name="牙と爪", price=14, kind="material",
         desc="獣の牙。細工物の素材。", icon=("fang", dict(col="f0ecd8"))),
    dict(id="nenneki", name="粘液", price=12, kind="material",
         desc="ウーズから採る粘液。接着剤と、磨き粉になる。", icon=("slime", dict(col="78b068"))),
    dict(id="honekuzu", name="骨片", price=6, kind="material",
         desc="アンデッドの骨。骨粉にして、畑に撒く。", icon=("bone", dict(col="dcd8c8"))),
    dict(id="hakatsuchi", name="墓土", price=10, kind="material",
         desc="アンデッドに付いた土。神殿が清めて、買い取る。", icon=("lump", dict(col="4a4038", kind="dung"))),
    dict(id="tetsukuzu", name="鉄屑", price=12, kind="material",
         desc="壊れた魔導体の部品。鍛冶組が溶かす。", icon=("scrap", dict(col="8a90a0"))),
    dict(id="ma_ha", name="魔草の葉", price=14, kind="material",
         desc="動く草木から採れる葉。薬草より効く。", icon=("herb", dict(col="3a9a50", flower=None))),
    dict(id="yakeishi", name="焼け石", price=20, kind="material",
         desc="精霊が崩れた跡に残る、熱い石。燃料になる。", icon=("lump", dict(col="d85a2a", kind="ember"))),
    dict(id="uroko", name="魔物の鱗", price=40, kind="material",
         desc="硬い鱗。鎧の継ぎ目に使う。", icon=("scale", dict(col="5aa890"))),
    dict(id="doku_sen", name="毒腺", price=32, kind="material",
         desc="蜘蛛や蛇の毒の袋。薬師組が、毒消しに加工する。", icon=("gland", dict(col="a0d040"))),
    dict(id="hane", name="羽", price=12, kind="material",
         desc="飛ぶ魔物の羽。矢羽や、飾りになる。", icon=("feather", dict(col="e8e0d0"))),
    # --- 遺品(死体から) ---
    dict(id="relic_gear", name="遺品の装備", price=90, kind="material",
         desc="先に来た者の装備一式。ギルドの遺品課に届けると、謝礼が出る。", icon=("bundle", dict(col="8a90a0", kind="gear"))),
    dict(id="relic_tools", name="遺品の道具", price=40, kind="material",
         desc="錆びていない道具一揃い。", icon=("bundle", dict(col="8a6a48", kind="tools"))),
    dict(id="relic_tag", name="認識票", price=50, kind="material",
         desc="冒険者の首にかかっていた札。遺族に届けると、謝礼が出る。", icon=("tag", dict(col="b8b8c8"))),
    dict(id="relic_coins", name="古い銀貨", price=15, kind="material",
         desc="袋に残っていた、少しの銀貨。", icon=("coins", dict(col="d8d8e0"))),
]

# ---- 魔物が落とすもの: (対象, 品物, 確率, 条件) ----
#   対象: 魔物の type(beast など)か、index の一部。cr の下限は、最後の値
DROPS = [
    ("type:beast", "kemono_niku", 0.30, 0.0),
    ("type:beast", "kemono_kawa", 0.18, 0.0),
    ("type:beast", "kiba", 0.20, 0.0),
    ("type:ooze", "nenneki", 0.45, 0.0),
    ("type:undead", "honekuzu", 0.40, 0.0),
    ("type:undead", "hakatsuchi", 0.20, 0.0),
    ("type:construct", "tetsukuzu", 0.50, 0.0),
    ("type:plant", "ma_ha", 0.45, 0.0),
    ("type:fey", "ma_ha", 0.30, 0.0),
    ("type:elemental", "yakeishi", 0.45, 0.0),
    ("type:dragon", "uroko", 0.50, 0.0),
    ("type:monstrosity", "uroko", 0.15, 0.0),
    ("type:monstrosity", "kiba", 0.20, 0.0),
    ("type:fiend", "yakeishi", 0.25, 0.0),
    ("idx:spider", "doku_sen", 0.35, 0.0),
    ("idx:snake", "doku_sen", 0.30, 0.0),
    ("idx:bat", "hane", 0.25, 0.0),
    ("idx:eagle", "hane", 0.35, 0.0),
    ("idx:owl", "hane", 0.35, 0.0),
    ("idx:raven", "hane", 0.35, 0.0),
    ("idx:hawk", "hane", 0.35, 0.0),
    ("idx:harpy", "hane", 0.40, 0.0),
]
